/* ============================================================
   Ghost Fleet — Live Maritime Tracker
   ============================================================
   Loads vessel data from the pipeline JSON output and renders
   an interactive dark-themed map with risk scoring, cargo load
   status, and economic estimates.

   Data source: dashboard/data/vessels.json
   (generated by dark_fleet_pipeline.py)
   ============================================================ */

// ── Config ──────────────────────────────────────────────────
const DATA_URL = "data/vessels.json";
const SIGNAL_URL = "../sanctioned_oil_flow_signal.json";

// Known transshipment hotspot zones (lat, lng, radiusKm, name)
const SAR_ZONES = [
    { lat: 45.3, lng: 36.6, radius: 80000, name: "Kerch Strait" },
    { lat: 36.5, lng: 22.8, radius: 60000, name: "Laconian Gulf" },
    { lat: 35.9, lng: -5.3, radius: 40000, name: "Strait of Gibraltar / Ceuta" },
    { lat: 4.5,  lng: 104.0, radius: 70000, name: "Strait of Malacca" },
    { lat: 1.2,  lng: 104.2, radius: 50000, name: "Singapore Strait" },
    { lat: 25.5, lng: 56.5, radius: 60000, name: "Strait of Hormuz" },
    { lat: 12.5, lng: 43.3, radius: 50000, name: "Bab el-Mandeb" },
];

// Simulated vessel positions (for demo without live AIS feed).
// In production this would come from AIS/GFW position API.
// These are realistic coordinates in known shadow-fleet corridors.
function generateDemoPositions(count) {
    const corridors = [
        // Black Sea / Kerch area
        { latMin: 43, latMax: 46, lngMin: 32, lngMax: 40, weight: 0.3 },
        // Mediterranean / Laconian Gulf
        { latMin: 34, latMax: 38, lngMin: 18, lngMax: 28, weight: 0.25 },
        // Indian Ocean / Arabian Sea
        { latMin: 10, latMax: 25, lngMin: 55, lngMax: 70, weight: 0.2 },
        // Southeast Asia / Malacca
        { latMin: -2, latMax: 8, lngMin: 98, lngMax: 108, weight: 0.15 },
        // West Africa
        { latMin: 0, latMax: 10, lngMin: -10, lngMax: 5, weight: 0.1 },
    ];

    const positions = [];
    for (let i = 0; i < count; i++) {
        // Pick corridor based on weight
        const r = Math.random();
        let cumWeight = 0;
        let corridor = corridors[0];
        for (const c of corridors) {
            cumWeight += c.weight;
            if (r <= cumWeight) { corridor = c; break; }
        }
        positions.push({
            lat: corridor.latMin + Math.random() * (corridor.latMax - corridor.latMin),
            lng: corridor.lngMin + Math.random() * (corridor.lngMax - corridor.lngMin),
        });
    }
    return positions;
}

// ── Utilities ───────────────────────────────────────────────

function formatUSD(value) {
    if (value >= 1_000_000_000) return "$" + (value / 1_000_000_000).toFixed(1) + "B";
    if (value >= 1_000_000) return "$" + (value / 1_000_000).toFixed(1) + "M";
    if (value >= 1_000) return "$" + (value / 1_000).toFixed(0) + "K";
    return "$" + value.toFixed(0);
}

function formatNumber(n) {
    return n != null ? n.toLocaleString() : "—";
}

function riskClass(score) {
    if (score >= 80) return "risk-critical";
    if (score >= 60) return "risk-high";
    if (score >= 40) return "risk-medium";
    return "risk-low";
}

function riskColor(score) {
    if (score >= 80) return "#ef4444";
    if (score >= 60) return "#f97316";
    if (score >= 40) return "#eab308";
    return "#22c55e";
}

// ── Map Setup ───────────────────────────────────────────────

const map = L.map("map", {
    center: [30, 40],
    zoom: 3,
    zoomControl: false,
    attributionControl: false,
});

// Dark ocean tile layer
L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png", {
    maxZoom: 18,
    subdomains: "abcd",
}).addTo(map);

L.control.zoom({ position: "topright" }).addTo(map);
L.control.attribution({ position: "bottomright", prefix: false })
    .addAttribution('Tiles © <a href="https://carto.com/">CARTO</a>')
    .addTo(map);

// Layer groups
const vesselLayer = L.layerGroup().addTo(map);
const sarLayer = L.layerGroup();
const encounterLayer = L.layerGroup();

let sarVisible = false;
let encountersVisible = false;

// ── SAR Overlay Zones ───────────────────────────────────────

SAR_ZONES.forEach(zone => {
    const circle = L.circle([zone.lat, zone.lng], {
        radius: zone.radius,
        color: "rgba(239, 68, 68, 0.5)",
        fillColor: "rgba(239, 68, 68, 0.08)",
        fillOpacity: 0.8,
        weight: 1,
        dashArray: "8, 5",
    });
    circle.bindTooltip(`🛰️ SAR Watch Zone: ${zone.name}`, {
        className: "sar-tooltip",
    });
    sarLayer.addLayer(circle);
});

// ── State ───────────────────────────────────────────────────

let allVessels = [];
let vesselMarkers = {};

// ── Load Data ───────────────────────────────────────────────

async function loadData() {
    try {
        const resp = await fetch(DATA_URL);
        if (!resp.ok) throw new Error("vessels.json not found");
        const data = await resp.json();
        allVessels = data.vessels || [];
    } catch (e) {
        console.warn("Could not load vessels.json, using demo data:", e.message);
        allVessels = generateDemoVessels();
    }

    // Load signal data
    try {
        const sigResp = await fetch(SIGNAL_URL);
        if (sigResp.ok) {
            const signal = await sigResp.json();
            updateSignalPanel(signal);
        }
    } catch (e) {
        console.warn("Could not load signal JSON:", e.message);
    }

    renderVessels();
    updateStats();
    renderVesselList();
}

function generateDemoVessels() {
    // Generate realistic demo data if pipeline hasn't been run yet
    const names = [
        "SORMOVSKIY 49", "ABYSS VOYAGER", "DARK HORIZON", "PHANTOM TIDE",
        "SHADOW MONARCH", "CRIMSON WAVE", "GHOST RUNNER", "IRON MAIDEN II",
        "STEEL SERPENT", "NIGHT CRAWLER", "BLACK PEARL", "VOID DANCER",
        "STORM HERALD", "ROGUE EMPRESS", "DARK FRONTIER", "SILENT PREDATOR",
        "OCEAN WRAITH", "STEEL GHOST", "PHANTOM CARGO", "IRON DRIFTER",
    ];
    const positions = generateDemoPositions(names.length);
    return names.map((name, i) => ({
        imo: `${9100000 + i * 1234}`,
        name,
        gfw_match: Math.random() > 0.2,
        identity_changes: Math.floor(Math.random() * 5),
        encounters: Math.floor(Math.random() * 10),
        risk_score: Math.floor(30 + Math.random() * 70),
        cargo_status: ["LOADED", "BALLAST", "UNKNOWN"][Math.floor(Math.random() * 3)],
        cargo_confidence: parseFloat((0.5 + Math.random() * 0.5).toFixed(2)),
        draft_m: parseFloat((5 + Math.random() * 15).toFixed(1)),
        speed_knots: parseFloat((8 + Math.random() * 8).toFixed(1)),
        est_cargo_barrels: [200000, 350000, 500000, 700000, 1400000][Math.floor(Math.random() * 5)],
        est_cargo_value_usd: 0,
        est_annual_flow_usd: 0,
        _lat: positions[i].lat,
        _lng: positions[i].lng,
    })).map(v => {
        v.est_cargo_value_usd = v.est_cargo_barrels * 78.5;
        v.est_annual_flow_usd = v.est_cargo_barrels * Math.max(v.encounters, 4) * 78.5;
        return v;
    });
}

// ── Render Vessels on Map ───────────────────────────────────

function renderVessels() {
    vesselLayer.clearLayers();
    vesselMarkers = {};

    const positions = allVessels.some(v => v._lat)
        ? null
        : generateDemoPositions(allVessels.length);

    allVessels.forEach((vessel, i) => {
        const lat = vessel._lat || (positions ? positions[i].lat : 0);
        const lng = vessel._lng || (positions ? positions[i].lng : 0);

        // Store position on vessel for later use
        vessel._lat = lat;
        vessel._lng = lng;

        const rc = riskClass(vessel.risk_score);
        const marker = L.marker([lat, lng], {
            icon: L.divIcon({
                className: `vessel-marker ${rc}`,
                iconSize: [14, 14],
                iconAnchor: [7, 7],
            }),
            zIndexOffset: vessel.risk_score * 10,
        });

        // Tooltip
        const cargoTag = vessel.cargo_status || "UNKNOWN";
        marker.bindTooltip(
            `<b>${vessel.name}</b><br>` +
            `IMO: ${vessel.imo}<br>` +
            `Risk: ${vessel.risk_score} | Cargo: ${cargoTag}<br>` +
            `Value: ${formatUSD(vessel.est_cargo_value_usd || 0)}`,
            { className: "vessel-tooltip", direction: "top", offset: [0, -10] }
        );

        marker.on("click", () => showVesselDetail(vessel));
        vesselLayer.addLayer(marker);
        vesselMarkers[vessel.imo] = marker;
    });
}

// ── Encounter Lines ─────────────────────────────────────────

function renderEncounters() {
    encounterLayer.clearLayers();
    // Draw lines between high-risk vessels that are close together (simulated STS)
    const highRisk = allVessels.filter(v => v.risk_score >= 60 && v.encounters > 0);
    for (let i = 0; i < highRisk.length; i++) {
        for (let j = i + 1; j < highRisk.length; j++) {
            const a = highRisk[i], b = highRisk[j];
            const dist = Math.sqrt(Math.pow(a._lat - b._lat, 2) + Math.pow(a._lng - b._lng, 2));
            if (dist < 5) { // within ~5 degrees
                const line = L.polyline(
                    [[a._lat, a._lng], [b._lat, b._lng]],
                    { color: "#a78bfa", weight: 1.5, dashArray: "4, 6", opacity: 0.6 }
                );
                line.bindTooltip(`⚠️ Potential STS: ${a.name} ↔ ${b.name}`, { sticky: true });
                encounterLayer.addLayer(line);
            }
        }
    }
}

// ── Stats Bar ───────────────────────────────────────────────

function updateStats() {
    document.getElementById("stat-total").textContent = allVessels.length;
    document.getElementById("stat-highrisk").textContent =
        allVessels.filter(v => v.risk_score >= 70).length;
    document.getElementById("stat-loaded").textContent =
        allVessels.filter(v => v.cargo_status === "LOADED").length;

    const activeCargoValue = allVessels
        .filter(v => v.cargo_status === "LOADED" && v.risk_score >= 70)
        .reduce((sum, v) => sum + (v.est_cargo_value_usd || 0), 0);
    document.getElementById("stat-cargo-value").textContent = formatUSD(activeCargoValue);
}

// ── Signal Panel ────────────────────────────────────────────

function updateSignalPanel(signal) {
    if (!signal) {
        // Compute from vessel data
        signal = computeSignalFromVessels();
    }

    document.getElementById("sig-brent").textContent = "$" + (signal.brent_crude_usd || 78.5).toFixed(2);
    document.getElementById("sig-fleet").textContent = signal.high_risk_vessels || "—";
    document.getElementById("sig-loadratio").textContent =
        `${signal.vessels_loaded || 0} / ${signal.vessels_ballast || 0}`;
    document.getElementById("sig-annual").textContent =
        formatUSD(signal.est_annual_sanctioned_flow_usd || 0);
    document.getElementById("sig-active").textContent =
        formatUSD(signal.est_active_cargo_value_usd || 0);

    // Risk tier overlay
    const tierEl = document.getElementById("tier-value");
    tierEl.textContent = signal.risk_tier || "—";
    tierEl.className = "tier-value tier-" + (signal.risk_tier || "MODERATE");
    document.getElementById("tier-flow").textContent =
        formatUSD(signal.est_annual_sanctioned_flow_usd || 0) + " / year";
}

function computeSignalFromVessels() {
    const highRisk = allVessels.filter(v => v.risk_score >= 70);
    const loaded = highRisk.filter(v => v.cargo_status === "LOADED").length;
    const ballast = highRisk.filter(v => v.cargo_status === "BALLAST").length;
    const totalAnnual = highRisk.reduce((s, v) => s + (v.est_annual_flow_usd || 0), 0);
    const activeCargo = highRisk
        .filter(v => v.cargo_status === "LOADED")
        .reduce((s, v) => s + (v.est_cargo_value_usd || 0), 0);

    return {
        brent_crude_usd: 78.5,
        high_risk_vessels: highRisk.length,
        vessels_loaded: loaded,
        vessels_ballast: ballast,
        est_annual_sanctioned_flow_usd: totalAnnual,
        est_active_cargo_value_usd: activeCargo,
        risk_tier: totalAnnual > 5e9 ? "CRITICAL" : totalAnnual > 1e9 ? "HIGH" : totalAnnual > 5e8 ? "ELEVATED" : "MODERATE",
    };
}

// ── Vessel Detail ───────────────────────────────────────────

function showVesselDetail(vessel) {
    document.getElementById("panel-signal").style.display = "none";
    document.getElementById("panel-vessel").style.display = "block";

    document.getElementById("vessel-name").textContent = vessel.name;
    document.getElementById("vessel-imo").textContent = "IMO: " + vessel.imo;

    const scoreEl = document.getElementById("vessel-risk-score");
    scoreEl.textContent = vessel.risk_score;

    const badge = document.getElementById("vessel-risk-badge");
    badge.className = "risk-badge-large " + riskClass(vessel.risk_score);

    // Cargo status
    const statusEl = document.getElementById("vessel-cargo-status");
    statusEl.textContent = vessel.cargo_status || "UNKNOWN";
    statusEl.className = "detail-value status-" + (vessel.cargo_status || "UNKNOWN");

    document.getElementById("vessel-cargo-conf").textContent =
        vessel.cargo_confidence != null ? (vessel.cargo_confidence * 100).toFixed(0) + "%" : "—";
    document.getElementById("vessel-draft").textContent =
        vessel.draft_m != null ? vessel.draft_m.toFixed(1) + " m" : "—";
    document.getElementById("vessel-speed").textContent =
        vessel.speed_knots != null ? vessel.speed_knots.toFixed(1) + " kn" : "—";
    document.getElementById("vessel-id-changes").textContent =
        vessel.identity_changes != null ? vessel.identity_changes : "—";
    document.getElementById("vessel-encounters").textContent =
        vessel.encounters != null ? vessel.encounters : "—";

    // Economic
    document.getElementById("vessel-barrels").textContent =
        formatNumber(vessel.est_cargo_barrels) + " bbl";
    document.getElementById("vessel-cargo-val").textContent =
        formatUSD(vessel.est_cargo_value_usd || 0);
    document.getElementById("vessel-annual").textContent =
        formatUSD(vessel.est_annual_flow_usd || 0);

    // Risk breakdown bar
    const sanctions = vessel.gfw_match !== false ? 40 : 40;
    const identity = Math.min((vessel.identity_changes || 0) * 10, 30);
    const encounters = Math.min((vessel.encounters || 0) * 5, 30);
    const total = sanctions + identity + encounters;

    document.getElementById("bar-sanctions").style.width = (sanctions / 100 * 100) + "%";
    document.getElementById("bar-identity").style.width = (identity / 100 * 100) + "%";
    document.getElementById("bar-encounters").style.width = (encounters / 100 * 100) + "%";

    // Pan map to vessel
    if (vessel._lat && vessel._lng) {
        map.flyTo([vessel._lat, vessel._lng], 6, { duration: 1.5 });
    }
}

// ── Vessel List ─────────────────────────────────────────────

function renderVesselList(filter = "") {
    const container = document.getElementById("vessel-list");
    container.innerHTML = "";

    const filtered = allVessels
        .filter(v => {
            if (!filter) return true;
            const q = filter.toLowerCase();
            return (v.name || "").toLowerCase().includes(q) ||
                   (v.imo || "").toLowerCase().includes(q);
        })
        .sort((a, b) => b.risk_score - a.risk_score);

    filtered.forEach(vessel => {
        const row = document.createElement("div");
        row.className = "vessel-row";
        row.onclick = () => showVesselDetail(vessel);

        const rc = riskClass(vessel.risk_score);
        const statusClass = vessel.cargo_status || "UNKNOWN";

        row.innerHTML = `
            <div class="vessel-row-risk ${rc}" style="border-color: ${riskColor(vessel.risk_score)}; color: ${riskColor(vessel.risk_score)}">
                ${vessel.risk_score}
            </div>
            <div class="vessel-row-info">
                <div class="vessel-row-name">${vessel.name || "UNKNOWN"}</div>
                <div class="vessel-row-meta">IMO ${vessel.imo} · ${formatUSD(vessel.est_cargo_value_usd || 0)}</div>
            </div>
            <div class="vessel-row-cargo ${statusClass}">${statusClass}</div>
        `;
        container.appendChild(row);
    });
}

// ── Event Listeners ─────────────────────────────────────────

document.getElementById("btn-toggle-sar").addEventListener("click", function () {
    sarVisible = !sarVisible;
    if (sarVisible) {
        sarLayer.addTo(map);
        this.classList.add("active");
    } else {
        map.removeLayer(sarLayer);
        this.classList.remove("active");
    }
});

document.getElementById("btn-toggle-encounters").addEventListener("click", function () {
    encountersVisible = !encountersVisible;
    if (encountersVisible) {
        renderEncounters();
        encounterLayer.addTo(map);
        this.classList.add("active");
    } else {
        map.removeLayer(encounterLayer);
        this.classList.remove("active");
    }
});

document.getElementById("btn-back-signal").addEventListener("click", () => {
    document.getElementById("panel-vessel").style.display = "none";
    document.getElementById("panel-signal").style.display = "block";
});

document.getElementById("vessel-search").addEventListener("input", (e) => {
    renderVesselList(e.target.value);
});

document.getElementById("sidebar-toggle").addEventListener("click", function () {
    const sidebar = document.getElementById("sidebar");
    if (sidebar.style.display === "none") {
        sidebar.style.display = "";
        this.textContent = "›";
    } else {
        sidebar.style.display = "none";
        this.textContent = "‹";
    }
});

// ── Tooltip Styling (injected) ──────────────────────────────

const tooltipStyle = document.createElement("style");
tooltipStyle.textContent = `
    .vessel-tooltip {
        background: rgba(17, 24, 39, 0.95) !important;
        border: 1px solid rgba(255,255,255,0.1) !important;
        border-radius: 8px !important;
        padding: 8px 12px !important;
        color: #f1f5f9 !important;
        font-family: 'Inter', sans-serif !important;
        font-size: 12px !important;
        line-height: 1.5 !important;
        box-shadow: 0 8px 24px rgba(0,0,0,0.4) !important;
    }
    .vessel-tooltip .leaflet-tooltip-tip {
        border-top-color: rgba(17, 24, 39, 0.95) !important;
    }
    .sar-tooltip {
        background: rgba(239, 68, 68, 0.9) !important;
        border: none !important;
        border-radius: 6px !important;
        color: white !important;
        font-family: 'Inter', sans-serif !important;
        font-size: 11px !important;
        font-weight: 600 !important;
        letter-spacing: 0.5px !important;
    }
`;
document.head.appendChild(tooltipStyle);

// ── Initialize ──────────────────────────────────────────────

loadData().then(() => {
    // Compute signal from vessel data if signal JSON wasn't loaded
    if (document.getElementById("sig-fleet").textContent === "—") {
        updateSignalPanel(computeSignalFromVessels());
    }
});
